### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by SaMochaxD** [MicrosoftStudentChapter/mlsctiet#12]

**Comment by adityapathakk** [comment]
I can take this up.

**Comment by Ave-Eren** [comment]
I would like to take this up as well.

**Comment by Ikshan-Tango** [comment]
Things we achieved:-

Established the complete template of the Sponsors page like it is on Figma within 2 days
"Want to sponsor us for the upcoming event?" form is now functioning, I used react hooks for that.
I personally looked over the react JS part as my teammates were still learning react JS.

Challenges we faced:-

1) Establishing the Carousel using swiper JS
2) Responsiveness of the website

Tasks that are left:-

1) Responsiveness of the website

Things we can improve upon:-

1) Some carousel-related bugs, we are using swiper.js 
2) Additional Elements/Vectors can be added to make the website a little more pleasing, it looks bland

**Comment by adityapathakk** [comment]
When this issue was assigned to me, I had just begun to learn the Javascript framework, React. With help from my teammates and consistency, I contributed to the page and solved challenges that we faced while trying to remake the page just like it was designed in Figma.

I agree with @Ikshan-Tango , we can implement some more graphics to make the page a little more lively.
